import tkinter as tk
from tkinter import messagebox
root=tk.Tk() 
root.geometry('700x700')
tk.Label(root, text="Анкета ученика",background="#FF0000",relief="raised",font=("Cascadia Code",12)).grid(row=0, column=150,sticky="ew")
tk.Label(root, text="Имя:",background="#00FF00",relief="raised",font=("Cascadia Code",10)).grid(row=1, column=0,sticky="ew")
tk.Entry(root,background="#808080").grid(row=1, column=100, padx=0, pady=5)
tk.Label(root, text="Фамилия:",background="#00FF00",relief="raised",font=("Cascadia Code",10)).grid(row=2, column=0,sticky="ew")
tk.Entry(root,background="#808080").grid(row=2, column=100, padx=0, pady=5)
tk.Label(root, text="Отчество:",background="#00FF00",relief="raised",font=("Cascadia Code",10)).grid(row=3, column=0,sticky="ew")
tk.Entry(root,background="#808080").grid(row=3, column=100, padx=0, pady=5)
tk.Label(root, text="Возраст:",background="#00FF00",relief="raised",font=("Cascadia Code",10)).grid(row=4, column=0,sticky="ew")
tk.Entry(root,background="#808080").grid(row=4, column=100, padx=0, pady=5)
tk.Label(root, text="Класс(номер,буква):",background="#00FF00",relief="raised",font=("Cascadia Code",10)).grid(row=5, column=0,sticky="ew")
tk.Entry(root,background="#808080").grid(row=5, column=100, padx=0, pady=5)
tk.Label(root, text="Классный руководитель:",background="#00FF00",relief="raised",font=("Cascadia Code",10)).grid(row=6, column=0,sticky="ew")
tk.Entry(root,background="#808080").grid(row=6, column=100, padx=0, pady=5)
root.mainloop()
